version: '3.8'

services:
  backend-test:
    build: ./backend
    environment:
      NODE_ENV: test
    command: npm test

  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    command: npm test