version: '3.8'

services:
  db:
    image: postgres:14
    container_name: todo-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: todo-backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: todo_db
      DB_PORT: 5432
      PORT: 3000
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: todo-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  postgres_data: